version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: users-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - users_pg_data:/var/lib/postgresql/data

volumes:
  users_pg_data: